name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        git clone https://github.com/fwilhe2/Artillery-Game
        cd Artillery-Game
        ./gradlew publishToMavenLocal
        cd ..
        ./gradlew check
